= Metered Billing
:page_audience: vshneer

include::partial$audience-hint.adoc[]

This documents describes how puppet managed services report data to Odoo for
service billing based on the measured usage.

More information regarding the metered billing at VSHN can be found at https://docs.central.vshn.ch/metered-billing.html

== Summary

The metered usage is leveraging the existing PuppetDB to determine billed services and components. Puppet profiles instantiate a defined resource type https://git.vshn.net/vshn-puppet/puppet-billing[Billing] which defines what unit and Odoo product ID should be used and to which sales order the usage of a specifc service should be reported.

The https://git.vshn.net/vshn-puppet/puppet-odoo-metered-billing-adapter[Puppet-Odoo metered billing adapter] will periodically query the PuppetDB for all `Billing` resources and submit them to VSHN central's https://docs.central.vshn.ch/metered-billing-data-ingestion.html[usage data ingestion endpoint]


=== Enable metered billing in a puppet profile

To enable metered billing for a puppet profile, that profile needs to define
a billing resource:

[source,puppet]
--
profile_example (
    ...,
    Billing::Options  $billing_custom_options = {},
    Optional[Boolean] $billing_reporting = undef,
    Optional[String]  $billing_sales_order_id = undef,
    ...,
){

  if $billing_reporting or $billing_reporting =~ Undef {
    billing { "${trusted['certname']}-${title}":
      product_id     => 'managed-service-...',
      reporting      => $billing_reporting,
      sales_order_id => $billing_sales_order_id,
      *              => $billing_custom_options,
    }
  }

}
--

[NOTE]
====
- Implement all parameters as outline above including their default values. This ensures an unified interface across all puppet profiles.
- Set the `product_id` to the corresponding `Metered Billing ID` of the product in https://central.vshn.ch/[Odoo]
====

=== Set billing information in hiera

For a resource to be processed in the metered billing, it needs to know to what sales order it should be reported. The `sales_order_id` needs to be configured in hiera:

[source,yaml]
--
billing::sales_order_id: 'Sxxxxx'
--

Alternativly, if different profiles should report to different sales orders, the `sales_order_id` may be overridden on a per-profile basis:

[source,yaml]
--
billing::sales_order_id: 'Syyyyy'
profile_specialservice::billing_sales_order_id: 'Szzzzz'
--

[NOTE]
====
Check with https://handbook.vshn.ch/domain_sales_account_management.html[Sales & Account Management] for the correct sales order to use for a specific project/service
====

=== Disable metered billing in hiera

Metered billing can be disabled for a specific profile or for a specific server or project in hiera

[source,yaml]
--
# disable billing for all services
billing::reporting: false

# disable for a specific profile
profile_specialservice::billing_reporting: false
--
